#mongo
spring:
  data:
    mongodb:
      database: madb
      host: localhost
      port: 27017

server:
  port: 8080

mycompagny:
  app:
    jwtSecret: roadTripPlannerSecretKey
    jwtExpirationMs: 86400000

